export const sampleData = [
  {
    dept: "Relation Manager -1",
    department: "RM-1",
    name: "Bargav",
    email: "bargav@thinklusive.com",
    contact: "+1(806)702-6470",
  },
  {
    dept: "Relation Manager -2",
    department: "RM-2",
    name: "Kumar",
    email: "pkumar@thinklusive.com",
    contact: "+1(469) 961-7754",
  },
  {
    dept: "HR",
    department: "HR Dept",
    name: "HR",
    email: "hr@thinklusive.com",
    contact: "+1(732) 419-3704",
  },
  {
    dept: "Finance and Immigration",
    department: "",
    name: "Sri",
    email: "hr@thinklusive.com",
    contact: "+1(732) 419-3704",
  },
  {
    dept: "CEO and Sales Head",
    department: "Escalation",
    name: "Sambasiva Kanneganti",
    email: "sam@thinklusive.com",
    contact: "+1(972) 310-2265",
  },
  {
    dept: "",
    department: "",
    name: "Sid",
    email: "siddhartha@thinklusive.com",
    contact: "",
  },
  {
    dept: "BGV",
    department: "BGC",
    name: "Raj/Bargav",
    email: "rajendra@thinklusive.com",
    Phone: "",
  },
  {
    dept: "",
    department: "",
    name: "Bargav",
    email: "bargav@thinklusive.com",
    contact: "",
  },
  {
    dept: "Sales Off shore",
    department: "Offshore sales Lead",
    name: "Vidya",
    email: "vidyas@thinklusive.com",
    contact: "+91 9989813199",
  },
  {
    dept: "TimeSheets",
    department: "Timesheet",
    name: "Rajesh",
    email: "timesheets@thinklusive.com",
    contact: "+91 9884267267 ",
  },

  {
    dept: "",
    department: "Immigration",
    name: "Lakshman",
    email: "insmgrr@thinklusive.com",
    contact: "+91 9989310781 ",
  },
  {
    dept: "",
    department: "Employee Accounts",
    name: "Bindu",
    email: "hchintala@thinklusive.com",
    contact: "",
  },
];
