name: Market 360 Frontend Deploy to Azure VM

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: COPY-REPO-TO-DEV-SERVER
      uses: appleboy/scp-action@master
      with:
        host: '${{ secrets.VM_HOST }}'
        username: '${{ secrets.VM_USERNAME }}'
        key: '${{ secrets.SSH_PRIVATE_KEY }}'
        port: '${{ secrets.VM_SSH_PORT_NUMBER }}'
        source: "./"  # Copies the entire repo
        target: "/home/ubuntu/react/Market360UI"

    - name: Deploy-Frontend-App-To-Ubuntu-VM
      uses: appleboy/ssh-action@master
      with:
        host: '${{ secrets.VM_HOST }}'
        username: '${{ secrets.VM_USERNAME }}'
        key: '${{ secrets.SSH_PRIVATE_KEY }}'
        port: '${{ secrets.VM_SSH_PORT_NUMBER }}'
        script: |
          cd /home/ubuntu/react/Market360UI
          sudo npm install 
          sudo systemctl stop Market_360_Frontend.service
          sudo systemctl start Market_360_Frontend.service
          sudo systemctl status Market_360_Frontend.service
